import os

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.firefox.options import Options
from utils import File, Log, Time, TimeFormat

from workflows.TEAM_NAME_TO_ID import TEAM_NAME_TO_ID

URL = (
    'https://www.cricbuzz.com'
    + '/cricket-series/6732/icc-cricket-world-cup-2023/matches'
)
ODI_ID_TO_WINNER_JS = os.path.join(
    'src', 'nonview', 'data', 'ODI_ID_TO_WINNER.js'
)


log = Log('update_odi_id_to_winner')


def scrape_values_list() -> list[list[str]]:
    log.debug('scrape_values_list')
    options = Options()
    options.add_argument('-headless')
    driver = webdriver.Firefox(options=options)
    driver.get(URL)
    driver.implicitly_wait(2)

    screenshot_path = os.path.join('screenshot.odi_id_to_winner.png')
    driver.save_screenshot(screenshot_path)
    log.debug(f'Wrote {screenshot_path}')

    try:
        div_list = driver.find_elements(By.CLASS_NAME, 'cb-srs-mtchs-tm')
    except Exception as e:
        log.error(str(e))
        driver.quit()
        return {}

    values_list = []
    for div in div_list:
        if 'vs' not in div.text or 'won' not in div.text:
            continue
        values = div.text.split('\n')
        log.debug(str(values))
        values_list.append(values)
    driver.quit()
    return values_list


def get_odi_id_to_winner_id(values_list: list[list[str]]) -> dict[str, float]:
    log.debug('get_odi_id_to_winner_id')
    odi_id_to_winner_id = {}

    for i_odi, values in enumerate(values_list):
        odi_id = f'ODI {i_odi + 1:02d}'
        winner_name = values[2].split(' won ')[0]
        winner_id = TEAM_NAME_TO_ID[winner_name]
        odi_id_to_winner_id[odi_id] = winner_id
        log.debug(f'{odi_id} -> {winner_id}')
    log.info(str(odi_id_to_winner_id))
    return odi_id_to_winner_id


def write(odi_id_to_winner_id: dict[str, float]):
    lines = []
    timestamp = TimeFormat('%Y-%m-%d %H:%M:%S').stringify(Time.now())
    lines.extend(
        [
            '// Auto Generated by update_odi_id_to_winner_id.py',
            f'// {URL}',
            f'// {timestamp}',
            '',
            'import { TEAM } from "../core/Team.js";',
            '',
        ]
    )
    lines.append('export const ODI_ID_TO_WINNER = {')
    for odi_id, winner_id in odi_id_to_winner_id.items():
        line = f'  "{odi_id}": TEAM.{winner_id},'
        log.debug(line)
        lines.append(line)
    lines.extend(['};', ''])
    File(ODI_ID_TO_WINNER_JS).write_lines(lines)
    n_matches = len(odi_id_to_winner_id.keys())
    log.info(f'Wrote {n_matches} matches to {ODI_ID_TO_WINNER_JS}')


def main():
    values_list = scrape_values_list()
    odi_id_to_winner_id = get_odi_id_to_winner_id(values_list)
    write(odi_id_to_winner_id)


if __name__ == '__main__':
    main()
