import os

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.firefox.options import Options
from utils import File, Log, Time, TimeFormat

from workflows.TEAM_NAME_TO_ID import TEAM_NAME_TO_ID

URL = 'https://www.oddsportal.com' + '/cricket/world/icc-world-cup/'
odi_id_to_team_id_to_odds_JS = os.path.join(
    'src', 'nonview', 'data', 'ODI_ID_TO_TEAM_ID_TO_ODDS.js'
)


log = Log('update_odi_id_to_team_id_to_odds')


def scrape_values_list() -> list[list[str]]:
    log.debug('scrape_values_list')
    options = Options()
    options.add_argument('-headless')
    driver = webdriver.Firefox(options=options)
    driver.get(URL)
    driver.implicitly_wait(2)

    screenshot_path = os.path.join('screenshot.odi_id_to_team_id_to_odds.png')
    driver.save_screenshot(screenshot_path)
    log.debug(f'Wrote {screenshot_path}')

    try:
        div_list = driver.find_elements(By.CLASS_NAME, 'border-black-borders')
    except Exception as e:
        log.error(str(e))
        driver.quit()
        return {}

    values_list = []
    for div in div_list:
        values = div.text.split('\n')
        if len(values) <= 2 or values[2] != '–':
            continue
        log.debug(str(values))
        values_list.append(values)
    driver.quit()
    return values_list


def get_odi_id_to_team_id_to_odds(
    values_list: list[list[str]],
) -> dict[str, float]:
    log.debug('get_odi_id_to_team_id_to_odds')
    odi_id_to_team_id_to_odds = {}
    for values in values_list:
        if values[4] == '–':
            continue

        team1_name = values[1]
        team2_name = values[3]
        team1_id = TEAM_NAME_TO_ID[team1_name]
        team2_id = TEAM_NAME_TO_ID[team2_name]
        team1_odds = float(values[4])
        team2_odds = float(values[5])


        
    return odi_id_to_team_id_to_odds


def write(odi_id_to_team_id_to_odds: dict[str, float]):
    lines = []
    timestamp = TimeFormat('%Y-%m-%d %H:%M:%S').stringify(Time.now())
    lines.extend(
        [
            '// Auto Generated by'
            + ' workflows/update_odi_id_to_team_id_to_odds.py',
            f'// www.cricbuzz.com - {timestamp}',
            '',
            'import { TEAM } from "../core/Team.js";',
            '',
        ]
    )
    lines.append('export const odi_id_to_team_id_to_odds = {')
    for odi_id, team_id_to_odds in odi_id_to_team_id_to_odds.items():
        lines.append(f'  "{odi_id}": ' + '{')
        for team_id, odds in team_id_to_odds.items():
            lines.append(f'    TEAM.{team_id}.id: {odds:.4f},')
        lines.append('},')

    lines.extend(['};', ''])
    File(odi_id_to_team_id_to_odds_JS).write_lines(lines)
    n_matches = len(odi_id_to_team_id_to_odds.keys())
    log.info(f'Wrote {n_matches} matches to {odi_id_to_team_id_to_odds_JS}')


def main():
    values_list = scrape_values_list()
    odi_id_to_team_id_to_odds = get_odi_id_to_team_id_to_odds(values_list)
    write(odi_id_to_team_id_to_odds)


if __name__ == '__main__':
    main()
