import os

from utils import File, Log, Time, TimeFormat

VERSION_JS = os.path.join('src', 'nonview', 'constants', 'VERSION.js')
log = Log('update_version')


def main():
    datetime_str = TimeFormat('%Y-%m-%d %H:%M:%S').stringify(Time.now())
    last_commit_message = 'Updated 📊Data'
    lines = [
        '// Auto-generated by javascript_version.py',
        f'export const DATETIME_STR = "{datetime_str}";',
        'export const VERSION_DATETIME = new Date(DATETIME_STR);',
        f'export const LAST_COMMIT_MESSAGE = "{last_commit_message}"',
    ]
    File(VERSION_JS).write_lines(lines)
    log.info(f'Wrote {VERSION_JS}')


if __name__ == '__main__':
    main()
