// Auto Generated by workflows/main.py
import ODI from "./ODI.js";
import { TEAM } from "./Team.js";

export const GROUP_STAGE_ODI_LIST = [
  new ODI(
    "ODI 45",
    "2023-11-11",
    TEAM.IND,
    TEAM.NLD,
    "Bengaluru",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 44",
    "2023-11-12",
    TEAM.ENG,
    TEAM.PAK,
    "Kolkata",
    null,
    null,
    null
  ),
  new ODI("ODI 43", "2023-11-12", TEAM.AUS, TEAM.BGD, "Pune", null, null, null),
  new ODI(
    "ODI 42",
    "2023-11-10",
    TEAM.AFG,
    TEAM.ZAF,
    "Ahmedabad",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 41",
    "2023-11-09",
    TEAM.NZL,
    TEAM.LKA,
    "Bengaluru",
    null,
    null,
    null
  ),
  new ODI("ODI 40", "2023-11-08", TEAM.ENG, TEAM.NLD, "Pune", null, null, null),
  new ODI(
    "ODI 39",
    "2023-11-07",
    TEAM.AUS,
    TEAM.AFG,
    "Mumbai",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 38",
    "2023-11-06",
    TEAM.BGD,
    TEAM.LKA,
    "Delhi",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 37",
    "2023-11-05",
    TEAM.IND,
    TEAM.ZAF,
    "Kolkata",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 36",
    "2023-11-04",
    TEAM.AUS,
    TEAM.ENG,
    "Ahmedabad",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 35",
    "2023-11-04",
    TEAM.NZL,
    TEAM.PAK,
    "Bengaluru",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 34",
    "2023-11-03",
    TEAM.AFG,
    TEAM.NLD,
    "Lucknow",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 33",
    "2023-11-02",
    TEAM.IND,
    TEAM.LKA,
    "Mumbai",
    null,
    null,
    null
  ),
  new ODI("ODI 32", "2023-11-01", TEAM.NZL, TEAM.ZAF, "Pune", null, null, null),
  new ODI(
    "ODI 31",
    "2023-10-31",
    TEAM.BGD,
    TEAM.PAK,
    "Kolkata",
    null,
    null,
    null
  ),
  new ODI("ODI 30", "2023-10-30", TEAM.AFG, TEAM.LKA, "Pune", null, null, null),
  new ODI(
    "ODI 29",
    "2023-10-29",
    TEAM.ENG,
    TEAM.IND,
    "Lucknow",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 28",
    "2023-10-28",
    TEAM.BGD,
    TEAM.NLD,
    "Kolkata",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 27",
    "2023-10-28",
    TEAM.AUS,
    TEAM.NZL,
    "Dharamshala",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 26",
    "2023-10-27",
    TEAM.PAK,
    TEAM.ZAF,
    "Chennai",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 25",
    "2023-10-26",
    TEAM.ENG,
    TEAM.LKA,
    "Bengaluru",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 24",
    "2023-10-25",
    TEAM.AUS,
    TEAM.NLD,
    "Delhi",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 23",
    "2023-10-24",
    TEAM.BGD,
    TEAM.ZAF,
    "Mumbai",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 22",
    "2023-10-23",
    TEAM.AFG,
    TEAM.PAK,
    "Chennai",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 21",
    "2023-10-22",
    TEAM.IND,
    TEAM.NZL,
    "Dharamshala",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 20",
    "2023-10-21",
    TEAM.ENG,
    TEAM.ZAF,
    "Mumbai",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 19",
    "2023-10-21",
    TEAM.NLD,
    TEAM.LKA,
    "Lucknow",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 18",
    "2023-10-20",
    TEAM.AUS,
    TEAM.PAK,
    "Bengaluru",
    null,
    null,
    null
  ),
  new ODI("ODI 17", "2023-10-19", TEAM.BGD, TEAM.IND, "Pune", null, null, null),
  new ODI(
    "ODI 16",
    "2023-10-18",
    TEAM.AFG,
    TEAM.NZL,
    "Chennai",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 15",
    "2023-10-17",
    TEAM.ZAF,
    TEAM.NLD,
    "Dharamshala",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 14",
    "2023-10-16",
    TEAM.AUS,
    TEAM.LKA,
    "Lucknow",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 13",
    "2023-10-15",
    TEAM.AFG,
    TEAM.ENG,
    "Delhi",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 12",
    "2023-10-14",
    TEAM.IND,
    TEAM.PAK,
    "Ahmedabad",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 11",
    "2023-10-14",
    TEAM.BGD,
    TEAM.NZL,
    "Chennai",
    null,
    null,
    null
  ),
  new ODI(
    "ODI 10",
    "2023-10-13",
    TEAM.AUS,
    TEAM.ZAF,
    "Lucknow",
    null,
    1.59,
    2.3
  ),
  new ODI("ODI 09", "2023-10-11", TEAM.AFG, TEAM.IND, "Delhi", null, 5.6, 1.13),
  new ODI(
    "ODI 08",
    "2023-10-10",
    TEAM.PAK,
    TEAM.LKA,
    "Hyderabad",
    null,
    1.52,
    2.46
  ),
  new ODI(
    "ODI 07",
    "2023-10-10",
    TEAM.BGD,
    TEAM.ENG,
    "Dharamshala",
    null,
    4.1,
    1.22
  ),
  new ODI(
    "ODI 06",
    "2023-10-09",
    TEAM.NZL,
    TEAM.NLD,
    "Hyderabad",
    null,
    1.11,
    6
  ),
  new ODI(
    "ODI 05",
    "2023-10-08",
    TEAM.AUS,
    TEAM.IND,
    "Chennai",
    null,
    2.32,
    1.67
  ),
  new ODI("ODI 04", "2023-10-07", TEAM.ZAF, TEAM.LKA, "Delhi", null, 1.5, 2.8),
  new ODI(
    "ODI 03",
    "2023-10-07",
    TEAM.AFG,
    TEAM.BGD,
    "Dharamshala",
    null,
    2.2,
    1.73
  ),
  new ODI(
    "ODI 02",
    "2023-10-06",
    TEAM.PAK,
    TEAM.NLD,
    "Hyderabad",
    null,
    1.06,
    13
  ),
  new ODI(
    "ODI 01",
    "2023-10-05",
    TEAM.ENG,
    TEAM.NZL,
    "Ahmedabad",
    null,
    1.47,
    2.8
  ),
];
