// Auto Generated by workflows/scrape_winner_odds.py
export const TEAM_ID_TO_P_WINNER = {
  IND: 0.310984, // 31.10%
  AUS: 0.182132, // 18.21%
  ENG: 0.148913, // 14.89%
  NZL: 0.124023, // 12.40%
  ZAF: 0.096821, // 9.68%
  PAK: 0.099332, // 9.93%
  LKA: 0.018577, // 1.86%
  BGD: 0.009865, // 0.99%
  AFG: 0.007536, // 0.75%
  NLD: 0.001815, // 0.18%
};
