// Auto-generated by javascript_version.py
export const DATETIME_STR = "2023-10-06 16:36:28";
export const VERSION_DATETIME = new Date(DATETIME_STR);
export const LAST_COMMIT_MESSAGE = "N_MONTE_CARLO_SIMULATIONS = 25_000";
