name: Update Data

# on: workflow_dispatch
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/20 * * * *'


jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install build

    - name: Checkout repo branch master
      uses: actions/checkout@v2
      with:
        ref: 'master'
        token: "${{ secrets.PAGES_TOKEN }}"

    - name: Run pipeline.py
      run: |
        export PYTHONPATH="$PYTHONPATH:./workflows"
        python workflows/update_data.py

    - name: Copy data, and push to repo branch master
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"

        echo "$(date) Update Data" >> update.log
        
        git add *
        git commit -m "Update Data $(date)"
        git push origin master
